b1: 0.5
b2: 0.99
alpha: 0.9
batch_size: 8
channels: 3
checkpoint_interval: 1
model:
checkpoints_dir:
dataset_name:
decay_epoch: 100
img_height: 256
img_width: 256
load_model: false
lr: 0.0001
n_cpu: 4
n_epochs: 100
sample_interval: 25
